//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HunterPie.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HunterPie.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Abnormalities&gt;
        ///  &lt;HUNTINGHORN_Abnormalities&gt;
        ///    &lt;Abnormality ID=&quot;0&quot; IsDebuff=&quot;False&quot; Offset=&quot;38&quot; Icon=&quot;ICON_SELFIMPROVEMENT&quot; Stack=&quot;0&quot;/&gt;
        ///    &lt;Abnormality ID=&quot;999&quot; IsDebuff=&quot;False&quot; Offset=&quot;38&quot; Icon=&quot;ICON_ATTACKUP&quot; Stack=&quot;1&quot;/&gt;
        ///    &lt;Abnormality ID=&quot;1&quot; IsDebuff=&quot;False&quot; Offset=&quot;3C&quot; Icon=&quot;ICON_ATTACKUP&quot; Stack=&quot;0&quot;/&gt;
        ///    &lt;Abnormality ID=&quot;2&quot; IsDebuff=&quot;False&quot; Offset=&quot;40&quot; Icon=&quot;ICON_ATTACKUP&quot; Stack=&quot;0&quot;/&gt;
        ///    &lt;Abnormality ID=&quot;3&quot; IsDebuff=&quot;False&quot; Offset=&quot;44&quot; Icon=&quot;ICON_HE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AbnormalityData {
            get {
                return ResourceManager.GetString("AbnormalityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon LOGO_HunterPie {
            get {
                object obj = ResourceManager.GetObject("LOGO_HunterPie", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Monsters&gt;
        ///  &lt;Monster ID=&quot;em001_00&quot;&gt;
        ///    &lt;Weaknesses&gt;
        ///      &lt;Weakness ID=&quot;ELEMENT_DRAGON&quot; Stars=&quot;3&quot;/&gt;
        ///      &lt;Weakness ID=&quot;ELEMENT_THUNDER&quot; Stars=&quot;2&quot;/&gt;
        ///    &lt;/Weaknesses&gt;
        ///    &lt;Crown Mini=&quot;90&quot; Silver=&quot;115&quot; Gold=&quot;123&quot;/&gt;
        ///    &lt;Parts Max=&quot;8&quot;&gt;
        ///      &lt;Part Name=&quot;MONSTER_PART_REMOVABLE_TAIL&quot; IsRemovable=&quot;True&quot;/&gt;
        ///      &lt;Part Name=&quot;MONSTER_PART_HEAD&quot; IsRemovable=&quot;False&quot;/&gt;
        ///      &lt;Part Name=&quot;MONSTER_PART_BODY&quot; IsRemovable=&quot;False&quot;/&gt;
        ///      &lt;Part Name=&quot;MONSTER_PART_LWING&quot;  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MonsterData {
            get {
                return ResourceManager.GetString("MonsterData", resourceCulture);
            }
        }
    }
}
