//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace HunterPie.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "15.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("HunterPie.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Abnormalities&gt;
        ///  &lt;HUNTINGHORN_Abnormalities&gt;
        ///    &lt;Abnormality ID=&quot;0&quot; IsDebuff=&quot;False&quot; Offset=&quot;38&quot; Icon=&quot;ICON_SELFIMPROVEMENT&quot; Stack=&quot;0&quot;/&gt;
        ///    &lt;Abnormality ID=&quot;999&quot; IsDebuff=&quot;False&quot; Offset=&quot;38&quot; Icon=&quot;ICON_ATTACKUP&quot; Stack=&quot;1&quot;/&gt;
        ///    &lt;Abnormality ID=&quot;1&quot; IsDebuff=&quot;False&quot; Offset=&quot;3C&quot; Icon=&quot;ICON_ATTACKUP&quot; Stack=&quot;0&quot;/&gt;
        ///    &lt;Abnormality ID=&quot;2&quot; IsDebuff=&quot;False&quot; Offset=&quot;40&quot; Icon=&quot;ICON_ATTACKUP&quot; Stack=&quot;0&quot;/&gt;
        ///    &lt;Abnormality ID=&quot;3&quot; IsDebuff=&quot;False&quot; Offset=&quot;44&quot; Icon=&quot;ICON_HE [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string AbnormalityData {
            get {
                return ResourceManager.GetString("AbnormalityData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Honey&gt;
        ///  &lt;Gear&gt;
        ///    &lt;Helms&gt;
        ///      &lt;Helm HoneyID=&quot;1&quot; ID=&quot;39&quot;/&gt;
        ///      &lt;Helm HoneyID=&quot;2&quot; ID=&quot;40&quot;/&gt;
        ///      &lt;Helm HoneyID=&quot;3&quot; ID=&quot;147&quot;/&gt;
        ///      &lt;Helm HoneyID=&quot;4&quot; ID=&quot;148&quot;/&gt;
        ///      &lt;Helm HoneyID=&quot;5&quot; ID=&quot;41&quot;/&gt;
        ///      &lt;Helm HoneyID=&quot;6&quot; ID=&quot;42&quot;/&gt;
        ///      &lt;Helm HoneyID=&quot;7&quot; ID=&quot;43&quot;/&gt;
        ///      &lt;Helm HoneyID=&quot;8&quot; ID=&quot;44&quot;/&gt;
        ///      &lt;Helm HoneyID=&quot;9&quot; ID=&quot;45&quot;/&gt;
        ///      &lt;Helm HoneyID=&quot;10&quot; ID=&quot;46&quot;/&gt;
        ///      &lt;Helm HoneyID=&quot;11&quot; ID=&quot;117&quot;/&gt;
        ///      &lt;Helm HoneyID=&quot;12&quot; ID=&quot;118&quot;/&gt;
        ///      &lt;Helm  [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string HoneyData {
            get {
                return ResourceManager.GetString("HoneyData", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon LOGO_HunterPie {
            get {
                object obj = ResourceManager.GetObject("LOGO_HunterPie", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to &lt;?xml version=&quot;1.0&quot; encoding=&quot;utf-8&quot; ?&gt;
        ///&lt;Monsters&gt;
        ///  &lt;Ailments Max=&quot;19&quot;&gt;
        ///    &lt;Ailment Name=&quot;0&quot; Skip=&quot;True&quot;/&gt;
        ///    &lt;Ailment Name=&quot;STATUS_POISON&quot; Skip=&quot;False&quot;/&gt;
        ///    &lt;Ailment Name=&quot;STATUS_PARALYSIS&quot; Skip=&quot;False&quot;/&gt;
        ///    &lt;Ailment Name=&quot;STATUS_SLEEP&quot; Skip=&quot;False&quot;/&gt;
        ///    &lt;Ailment Name=&quot;STATUS_BLAST&quot; Skip=&quot;False&quot;/&gt;
        ///    &lt;Ailment Name=&quot;STATUS_MOUNT&quot; Skip=&quot;False&quot;/&gt;
        ///    &lt;Ailment Name=&quot;STATUS_EXHAUSTION&quot; Skip=&quot;False&quot;/&gt;
        ///    &lt;Ailment Name=&quot;STATUS_STUN&quot; Skip=&quot;False&quot;/&gt;
        ///    &lt;Ailment Name=&quot;STATUS_TRANQUILIZE&quot; Skip=&quot;Fa [rest of string was truncated]&quot;;.
        /// </summary>
        internal static string MonsterData {
            get {
                return ResourceManager.GetString("MonsterData", resourceCulture);
            }
        }
    }
}
